sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t sredahan/hex-opacity -f Dockerfile.dev .

script:
  - docker run sredahan/hex-opacity npm run test -- --coverage

before_deploy:
  - yarn run build

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
